# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 
  pullPolicy: IfNotPresent
  tag: v2025-09-14-r1

containerPort: "5000"

config:
  KAFKA_HOST: 
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: producer_consumer
  KAFKA_CONSUMER_PASSWORD: 
  KAFKA_CONSUMER_GROUP: test_consumer
  KAFKA_SOURCE_TOPIC: dds-service-orders


  PG_WAREHOUSE_HOST: 
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: sprint9dwh
  PG_WAREHOUSE_USER: 
  PG_WAREHOUSE_PASSWORD: 

  REDIS_HOST:
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "12345678"

# imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
